# Generated by Django 5.1.1 on 2026-08-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('extra_motor', 'Extra Motor'), ('light', 'Light'), ('pipe', 'Pipe'), ('cable', 'Cable'), ('starter', 'Starter'), ('valve', 'Valve'), ('pump', 'Pump'), ('tools', 'Tools'), ('other', 'Other Material')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
